create table ITPROC
(
	ID INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(2000),
	RTO INT,
	Level NVARCHAR(30)
)

create table FACTOR
(
	ID INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(2000),
	Type NVARCHAR(30),	
)

create table RISK
(
	ID INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(2000),
	CITPROC INT,
	Damage DECIMAL(19,4)
	FOREIGN KEY(CITPROC) REFERENCES  ITPROC (ID)
)


create table ACTIVITY
(
	ID INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(2000),
	Summa DECIMAL(19,4),
	CFACTOR INT,
	IsActive BIT,
	FOREIGN KEY(CFACTOR) REFERENCES  FACTOR (ID)
)

create table FACTORRISK 
(
	ID INT PRIMARY KEY IDENTITY,
	CFACTOR INT,
	CRISK INT,
	[Set] INT,
	[Percent] FLOAT, 
	FOREIGN KEY(CFACTOR) REFERENCES  FACTOR (ID),
	FOREIGN KEY(CRISK) REFERENCES  RISK (ID)
)

create table REDUCTION
(
	ID INT PRIMARY KEY IDENTITY,
	CACTIVITY INT,
	CFACTORRISK INT,
	NewPercent Float
	FOREIGN KEY(CACTIVITY) REFERENCES  ACTIVITY (ID),
	FOREIGN KEY(CFACTORRISK) REFERENCES  FACTORRISK (ID),
)

create table RESULT
(
	ID INT PRIMARY KEY IDENTITY,
	CACTIVITY INT,
	StartRisk float,
	FinalRisk float,
	Cost float,
	Economy float
	FOREIGN KEY(CACTIVITY) REFERENCES  ACTIVITY (ID)
)

CREATE TABLE TEMPRESULT
(
	ID INT PRIMARY KEY IDENTITY,
	CRISK INT,
	Damage decimal(19, 4),
	CFACTOR INT,
	[SET] INT,
	[Percent] float
)